name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start LocalStack
        run: docker-compose -f docker-compose.yml up -d

      - name: Terraform init
        run: |
          cd terraform
          terraform init

      - name: Terraform validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform plan
        run: |
          cd terraform
          terraform plan